### ISSUE TITLE
Shift+right click should rotate counter-clockwise

### ISSUE THREAD

**Issue by tacotexmex** [12Me21/screwdriver2#2]
Since shift+left click inverts direction shift+right click should too.

**Comment by 12Me21** [comment]
I decided not to add this because you have to hold shift to right click nodes like chests, furnaces, etc.
I've always disliked items that do different things while you hold shift (for example, when you place logs, holding shift will change how the log is placed), because it prevents you from accessing the normal right click action when clicking nodes you can interact with.

**Comment by 12Me21** [comment]
I could make it so "special" (also called "use" or "aux1") reverses the direction.

**Comment by tacotexmex** [comment]
That’s too weird imo. Better then to keep it simple.
