### ISSUE TITLE
Not working with mesecons.

### ISSUE THREAD

**Issue by VorTechnix** [12Me21/screwdriver2#4]
As of the last mesecons update right-clicking on mesecons components (at least all the ones I've tested) no longer rotates them.

The issue is a change in how horizontal rotation is handled. Here is a link to the new code:
https://github.com/minetest-mods/mesecons/blob/960b7c4915574ae151f5682d4c2e2957441485f2/mesecons/util.lua#L20

Normal screwdriver works to rotate the nodes (I imagine they implemented the changes to make mesecons easier to use with normal screwdriver... although why anyone would do that is beyond me).

**Comment by 12Me21** [comment]
ah, that's not a good way to implement horizontal-only rotation...
They should be checking if the new `param2` is in [0,4). (or, use paramtype2 `4dir` instead of `facedir`)
Checking the rotation mode (i.e. right click vs left click) gives false positives and false negatives. it only *happens* to work with the default screwdriver.

I could add a hack to fix this, by checking if `on_rotate == mesecon.on_rotate_horiz` and setting the mode to a different value, but then you can still rotate to invalid states with left click, so i'd have to add a check for that too, etc..

**Comment by 12Me21** [comment]
The problem is basically,
my screwdriver represents rotation actions as an axis and an angle (e.g. "rotate [90°] about the [y] axis") which doesn't align with the default screwdriver (only 2 possible actions: `ROTATE_FACE` (increment the low 2 bits of the facedir) and `ROTATE_AXIS` (increment upper bits))
so, for `mode` i just pass 1 for left click and 2 for right click. (either of which could be a face rotation, an axis rotation, or a combination of the two)
but it seems like most mods just treat it as `ROTATE_FACE` = simple rotation, `ROTATE_AXIS` = complex rotation.
so perhaps i should just pass `ROTATE_FACE` if only the lower 2 bits have changed, and otherwise pass `ROTATE_AXIS` (even if i've changed both the axis and face)

**Comment by VorTechnix** [comment]
Thank you for your work on this! I really like screwdriver2 and I'm happy to be able to use it in mesecons projects again 😄.
